package eu.imagecode.scias.model.jpa;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientVersion generated by hbm2java
 */
@Entity
@Table(name = "client_version")
public class ClientVersionEntity implements java.io.Serializable {

    private int id;
    private Short major;
    private Short minor;
    private Date released;
    private Set<ClientEntity> clients = new HashSet<ClientEntity>(0);

    public ClientVersionEntity() {
    }

    public ClientVersionEntity(int id) {
        this.id = id;
    }

    public ClientVersionEntity(int id, Short major, Short minor, Date released, Set<ClientEntity> clients) {
        this.id = id;
        this.major = major;
        this.minor = minor;
        this.released = released;
        this.clients = clients;
    }

    @Id
    @SequenceGenerator(name = "CLIENT_VERSION_ID_GENERATOR", sequenceName = "CLIENT_VERSION_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CLIENT_VERSION_ID_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    @Column(name = "major")
    public Short getMajor() {
        return this.major;
    }

    public void setMajor(Short major) {
        this.major = major;
    }

    @Column(name = "minor")
    public Short getMinor() {
        return this.minor;
    }

    public void setMinor(Short minor) {
        this.minor = minor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "released", length = 29)
    public Date getReleased() {
        return this.released;
    }

    public void setReleased(Date released) {
        this.released = released;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "clientVersion")
    public Set<ClientEntity> getClients() {
        return this.clients;
    }

    public void setClients(Set<ClientEntity> clients) {
        this.clients = clients;
    }

}
