package eu.imagecode.scias.model.jpa;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", uniqueConstraints = @UniqueConstraint(columnNames = "version_id"))
public class ClientEntity implements java.io.Serializable {

    private int id;
    private ClientVersionEntity clientVersion;
    private Set<InputDataEntity> inputDatas = new HashSet<InputDataEntity>(0);
    private Set<ImageEntity> images = new HashSet<ImageEntity>(0);

    public ClientEntity() {
    }

    public ClientEntity(int id) {
        this.id = id;
    }

    public ClientEntity(int id, ClientVersionEntity clientVersion, Set<InputDataEntity> inputDatas,
                    Set<ImageEntity> images) {
        this.id = id;
        this.clientVersion = clientVersion;
        this.inputDatas = inputDatas;
        this.images = images;
    }

    @Id
    @SequenceGenerator(name = "CLIENT_ID_GENERATOR", sequenceName = "CLIENT_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CLIENT_ID_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "version_id", unique = true)
    public ClientVersionEntity getClientVersion() {
        return this.clientVersion;
    }

    public void setClientVersion(ClientVersionEntity clientVersion) {
        this.clientVersion = clientVersion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
    public Set<InputDataEntity> getInputDatas() {
        return this.inputDatas;
    }

    public void setInputDatas(Set<InputDataEntity> inputDatas) {
        this.inputDatas = inputDatas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
    public Set<ImageEntity> getImages() {
        return this.images;
    }

    public void setImages(Set<ImageEntity> images) {
        this.images = images;
    }

}
