package eu.imagecode.scias.model.jpa;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image")
public class ImageEntity implements java.io.Serializable {

    private int id;
    private ClientEntity client;
    private int localId;
    private String path;
    private String name;
    private String sha256;
    private Integer width;
    private Integer height;
    private Double pixelSize;
    private Date created;
    private MimeTypeEntity mimeType;
    private Set<UnclassifiedObjectEntity> unclassifiedObjects = new HashSet<UnclassifiedObjectEntity>(0);
    private Set<InputDataEntity> inputDatas = new HashSet<InputDataEntity>(0);

    public ImageEntity() {
    }

    public ImageEntity(int id, int localId, MimeTypeEntity mimeType) {
        this.id = id;
        this.localId = localId;
        this.mimeType = mimeType;
    }

    public ImageEntity(int id, ClientEntity client, int localId, String path, String name, String sha256, Integer width, Integer height,
                    Double pixelSize, Date created, MimeTypeEntity mimeType, Set<UnclassifiedObjectEntity> unclassifiedObjects,
                    Set<InputDataEntity> inputDatas) {
        this.id = id;
        this.client = client;
        this.localId = localId;
        this.path = path;
        this.name = name;
        this.sha256 = sha256;
        this.width = width;
        this.height = height;
        this.pixelSize = pixelSize;
        this.created = created;
        this.mimeType = mimeType;
        this.unclassifiedObjects = unclassifiedObjects;
        this.inputDatas = inputDatas;
    }

    @Id
    @SequenceGenerator(name = "IMAGE_ID_GENERATOR", sequenceName = "IMAGE_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "IMAGE_ID_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public ClientEntity getClient() {
        return this.client;
    }

    public void setClient(ClientEntity client) {
        this.client = client;
    }

    @Column(name = "local_id", nullable = false)
    public int getLocalId() {
        return this.localId;
    }

    public void setLocalId(int localId) {
        this.localId = localId;
    }

    @Column(name = "path", length = 4096)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Column(name = "name", length = 256)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "sha256", length = 256)
    public String getSha256() {
        return this.sha256;
    }

    public void setSha256(String sha256) {
        this.sha256 = sha256;
    }

    @Column(name = "width")
    public Integer getWidth() {
        return this.width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    @Column(name = "height")
    public Integer getHeight() {
        return this.height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    @Column(name = "pixel_size", precision = 17, scale = 17)
    public Double getPixelSize() {
        return this.pixelSize;
    }

    public void setPixelSize(Double pixelSize) {
        this.pixelSize = pixelSize;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", length = 29)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "mime_type", nullable = false, length = 16)
    public MimeTypeEntity getMimeType() {
        return this.mimeType;
    }

    public void setMimeType(MimeTypeEntity mimeType) {
        this.mimeType = mimeType;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
    public Set<UnclassifiedObjectEntity> getUnclassifiedObjects() {
        return this.unclassifiedObjects;
    }

    public void setUnclassifiedObjects(Set<UnclassifiedObjectEntity> unclassifiedObjects) {
        this.unclassifiedObjects = unclassifiedObjects;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
    public Set<InputDataEntity> getInputDatas() {
        return this.inputDatas;
    }

    public void setInputDatas(Set<InputDataEntity> inputDatas) {
        this.inputDatas = inputDatas;
    }

}
