package eu.imagecode.scias.model.jpa;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Locality generated by hbm2java
 */
@Entity
@Table(name = "locality")
public class LocalityEntity implements java.io.Serializable {

    private int id;
    private int localId;
    private double longtitude;
    private double latitude;
    private double altitude;
    private Set<SampleEntity> samples = new HashSet<SampleEntity>(0);

    public LocalityEntity() {
    }

    public LocalityEntity(int id, double longtitude, double latitude, double altitude) {
        this.id = id;
        this.longtitude = longtitude;
        this.latitude = latitude;
        this.altitude = altitude;
    }

    public LocalityEntity(int id, double longtitude, double latitude, double altitude, Set<SampleEntity> samples) {
        this.id = id;
        this.longtitude = longtitude;
        this.latitude = latitude;
        this.altitude = altitude;
        this.samples = samples;
    }

    @Id
    @SequenceGenerator(name = "LOCALITY_ID_GENERATOR", sequenceName = "LOCALITY_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "LOCALITY_ID_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "local_id", nullable = false)
    public int getLocalId() {
        return this.localId;
    }

    public void setLocalId(int localId) {
        this.localId = localId;
    }
    
    @Column(name = "longtitude", nullable = false, precision = 17, scale = 17)
    public double getLongtitude() {
        return this.longtitude;
    }

    public void setLongtitude(double longtitude) {
        this.longtitude = longtitude;
    }

    @Column(name = "latitude", nullable = false, precision = 17, scale = 17)
    public double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    @Column(name = "altitude", nullable = false, precision = 17, scale = 17)
    public double getAltitude() {
        return this.altitude;
    }

    public void setAltitude(double altitude) {
        this.altitude = altitude;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "locality")
    public Set<SampleEntity> getSamples() {
        return this.samples;
    }

    public void setSamples(Set<SampleEntity> samples) {
        this.samples = samples;
    }

}
