package eu.imagecode.scias.model.jpa;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Sample generated by hbm2java
 */
@Entity
@Table(name = "sample")
public class SampleEntity implements java.io.Serializable {

    private int id;
    private BatchEntity batch;
    private int localId;
    private Boolean finished;
    private LocalityEntity locality;
    private List<AnalysisEntity> analysises = new ArrayList<AnalysisEntity>(0);

    public SampleEntity() {
    }

    public SampleEntity(int id, int localId) {
        this.id = id;
        this.localId = localId;
    }

    public SampleEntity(int id, BatchEntity batch, int localId, Boolean finished) {
        this.id = id;
        this.batch = batch;
        this.localId = localId;
        this.finished = finished;
    }

    @Id
    @SequenceGenerator(name = "SAMPLE_ID_GENERATOR", sequenceName = "SAMPLE_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SAMPLE_ID_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "batch")
    public BatchEntity getBatch() {
        return this.batch;
    }

    public void setBatch(BatchEntity batch) {
        this.batch = batch;
    }

    @Column(name = "local_id", nullable = false)
    public int getLocalId() {
        return this.localId;
    }

    public void setLocalId(int localId) {
        this.localId = localId;
    }

    @Column(name = "finished")
    public Boolean isFinished() {
        return this.finished;
    }

    public void setFinished(Boolean finished) {
        this.finished = finished;
    }
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "locality_id")
    public LocalityEntity getLocality() {
        return this.locality;
    }

    public void setLocality(LocalityEntity locality) {
        this.locality = locality;
    }
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sample", cascade = CascadeType.ALL)
    public List<AnalysisEntity> getAnalyses() {
        return this.analysises;
    }

    public void setAnalyses(List<AnalysisEntity> analysises) {
        this.analysises = analysises;
    }

}
