package eu.imagecode.scias.model.jpa;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SciasUser generated by hbm2java
 */
@Entity
@Table(name = "scias_user")
public class SciasUserEntity implements java.io.Serializable {

    private int id;
    private String username;
    private String password;
    private Set<UserRoleEntity> userRoles = new HashSet<UserRoleEntity>(0);
    private Set<UnclassifiedObjectEntity> unclassifiedObjects = new HashSet<UnclassifiedObjectEntity>(0);

    public SciasUserEntity() {
    }

    public SciasUserEntity(int id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }

    public SciasUserEntity(int id, String username, String password, Set<UserRoleEntity> userRoles,
                    Set<UnclassifiedObjectEntity> unclassifiedObjects) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.userRoles = userRoles;
        this.unclassifiedObjects = unclassifiedObjects;
    }

    @Id
    @SequenceGenerator(name = "SCIAS_USER_ID_GENERATOR", sequenceName = "SCIAS_USER_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SCIAS_USER_ID_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "username", nullable = false, length = 256)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false, length = 256)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sciasUser")
    public Set<UserRoleEntity> getUserRoles() {
        return this.userRoles;
    }

    public void setUserRoles(Set<UserRoleEntity> userRoles) {
        this.userRoles = userRoles;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "resolvedBy")
    public Set<UnclassifiedObjectEntity> getUnclassifiedObjects() {
        return this.unclassifiedObjects;
    }

    public void setUnclassifiedObjects(Set<UnclassifiedObjectEntity> unclassifiedObjects) {
        this.unclassifiedObjects = unclassifiedObjects;
    }

}
