package eu.imagecode.scias.model.jpa;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SciasRole generated by hbm2java
 */
@Entity
@Table(name = "scias_role")
public class SciasRoleEntity implements java.io.Serializable {

    private int id;
    private String role;
    private String description;
    private Set<UserRoleEntity> userRoles = new HashSet<UserRoleEntity>(0);

    public SciasRoleEntity() {
    }

    public SciasRoleEntity(int id, String role) {
        this.id = id;
        this.role = role;
    }

    public SciasRoleEntity(int id, String role, String description, Set<UserRoleEntity> userRoles) {
        this.id = id;
        this.role = role;
        this.description = description;
        this.userRoles = userRoles;
    }

    @Id
    @SequenceGenerator(name = "SCIAS_ROLE_ID_GENERATOR", sequenceName = "SCIAS_ROLE_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SCIAS_ROLE_ID_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "role", nullable = false, length = 32)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Column(name = "description", length = 256)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sciasRole")
    public Set<UserRoleEntity> getUserRoles() {
        return this.userRoles;
    }

    public void setUserRoles(Set<UserRoleEntity> userRoles) {
        this.userRoles = userRoles;
    }

}
