package eu.imagecode.scias.model.jpa;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UnclassifiedObject generated by hbm2java
 */
@Entity
@Table(name = "unclassified_object")
public class UnclassifiedObjectEntity implements java.io.Serializable {

    private int id;
    private ImageEntity image;
    private ResultSetEntity resultSet;
    private SciasUserEntity resolvedBy;
    private int localId;
    private Integer classId;
    private Boolean resolved;
    private Date resolvedTime;
    private StationEntity station;

    public UnclassifiedObjectEntity() {
    }

    public UnclassifiedObjectEntity(int id, int localId) {
        this.id = id;
        this.localId = localId;
    }

    public UnclassifiedObjectEntity(int id, ImageEntity image, ResultSetEntity resultSet, SciasUserEntity sciasUser,
                    int localId, Integer classId, Boolean resolved, Date resolvedTime) {
        this.id = id;
        this.image = image;
        this.resultSet = resultSet;
        this.resolvedBy = sciasUser;
        this.localId = localId;
        this.classId = classId;
        this.resolved = resolved;
        this.resolvedTime = resolvedTime;
    }

    @Id
    @SequenceGenerator(name = "UNCLASSIFIED_OBJECT_ID_GENERATOR", sequenceName = "UNCLASSIFIED_OBJECT_ID_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "UNCLASSIFIED_OBJECT_ID_GENERATOR")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "image_id")
    public ImageEntity getImage() {
        return this.image;
    }

    public void setImage(ImageEntity image) {
        this.image = image;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "result_set_id")
    public ResultSetEntity getResultSet() {
        return this.resultSet;
    }

    public void setResultSet(ResultSetEntity resultSet) {
        this.resultSet = resultSet;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resolved_by_id")
    public SciasUserEntity getResolvedBy() {
        return this.resolvedBy;
    }

    public void setResolvedBy(SciasUserEntity sciasUser) {
        this.resolvedBy = sciasUser;
    }

    @Column(name = "local_id", nullable = false)
    public int getLocalId() {
        return this.localId;
    }

    public void setLocalId(int localId) {
        this.localId = localId;
    }

    @Column(name = "class_id")
    public Integer getClassId() {
        return this.classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    @Column(name = "resolved")
    public Boolean getResolved() {
        return this.resolved;
    }

    public void setResolved(Boolean resolved) {
        this.resolved = resolved;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "resolved_time", length = 29)
    public Date getResolvedTime() {
        return this.resolvedTime;
    }

    public void setResolvedTime(Date resolvedTime) {
        this.resolvedTime = resolvedTime;
    }
    
    @ManyToOne
    @JoinColumn(name = "station_id")
    public StationEntity getStation() {
        return this.station;
    }

    public void setStation(StationEntity station) {
        this.station = station;
    }

}
