package eu.imagecode.scias.model.jpa;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role")
public class UserRoleEntity implements java.io.Serializable {

    private UserRoleId id;
    private SciasRoleEntity sciasRole;
    private SciasUserEntity sciasUser;

    public UserRoleEntity() {
    }

    public UserRoleEntity(UserRoleId id, SciasRoleEntity sciasRole, SciasUserEntity sciasUser) {
        this.id = id;
        this.sciasRole = sciasRole;
        this.sciasUser = sciasUser;
    }

    @EmbeddedId
    @AttributeOverrides({
                    @AttributeOverride(name = "sciasUserId", column = @Column(name = "scias_user_id", nullable = false)),
                    @AttributeOverride(name = "sciasRoleId", column = @Column(name = "scias_role_id", nullable = false)) })
    public UserRoleId getId() {
        return this.id;
    }

    public void setId(UserRoleId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "scias_role_id", nullable = false, insertable = false, updatable = false)
    public SciasRoleEntity getSciasRole() {
        return this.sciasRole;
    }

    public void setSciasRole(SciasRoleEntity sciasRole) {
        this.sciasRole = sciasRole;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "scias_user_id", nullable = false, insertable = false, updatable = false)
    public SciasUserEntity getSciasUser() {
        return this.sciasUser;
    }

    public void setSciasUser(SciasUserEntity sciasUser) {
        this.sciasUser = sciasUser;
    }

}
